"""empty message

Revision ID: 1beabf0f13d4
Revises: 1ecf6ed3f65b
Create Date: 2023-03-21 14:24:32.018160

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1beabf0f13d4'
down_revision = '1ecf6ed3f65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tag_association',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tag_association')
    # ### end Alembic commands ###
