"""empty message

Revision ID: 2619ff683bf3
Revises: 1d9ceb83e01d
Create Date: 2023-03-16 14:26:00.238716

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2619ff683bf3'
down_revision = '1d9ceb83e01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
